# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c43f609f1e9805a33f288aec62daa4bb2a5b309321c1c1fc42903e5e8b965c81b35470823e676263421f61f9fa94ee796fdf7666ac47df44940a42290979b7eb

test:
  secret_key_base: 0a8d6454a039ca4420201ffbd7bd3d494147b3ff41b992be0b968733d0ff34bf8aad8bf679f878a49a7a9c949f7bcce1f7cde28b232285b35d525fe4a49fd864

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
